/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MailRouteImport } from './routes/mail'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MailIndexRouteImport } from './routes/mail.index'
import { Route as CalendarIndexRouteImport } from './routes/calendar.index'
import { Route as MailSearchRouteImport } from './routes/mail.search'
import { Route as MailComposeRouteImport } from './routes/mail.compose'
import { Route as CalendarViewRouteImport } from './routes/calendar.$view'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AttachmentsAttachmentIdRouteImport } from './routes/attachments.$attachmentId'
import { Route as ApiVersionRouteImport } from './routes/api.version'
import { Route as MailFFolderIdRouteImport } from './routes/mail.f.$folderId'
import { Route as ApiWebhooksNylasRouteImport } from './routes/api.webhooks.nylas'
import { Route as MailFFolderIdTThreadIdRouteImport } from './routes/mail.f.$folderId.t.$threadId'

const MailRoute = MailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MailIndexRoute = MailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MailRoute,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CalendarRoute,
} as any)
const MailSearchRoute = MailSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => MailRoute,
} as any)
const MailComposeRoute = MailComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => MailRoute,
} as any)
const CalendarViewRoute = CalendarViewRouteImport.update({
  id: '/$view',
  path: '/$view',
  getParentRoute: () => CalendarRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AttachmentsAttachmentIdRoute = AttachmentsAttachmentIdRouteImport.update({
  id: '/attachments/$attachmentId',
  path: '/attachments/$attachmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const MailFFolderIdRoute = MailFFolderIdRouteImport.update({
  id: '/f/$folderId',
  path: '/f/$folderId',
  getParentRoute: () => MailRoute,
} as any)
const ApiWebhooksNylasRoute = ApiWebhooksNylasRouteImport.update({
  id: '/api/webhooks/nylas',
  path: '/api/webhooks/nylas',
  getParentRoute: () => rootRouteImport,
} as any)
const MailFFolderIdTThreadIdRoute = MailFFolderIdTThreadIdRouteImport.update({
  id: '/t/$threadId',
  path: '/t/$threadId',
  getParentRoute: () => MailFFolderIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/calendar': typeof CalendarRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/mail': typeof MailRouteWithChildren
  '/api/version': typeof ApiVersionRoute
  '/attachments/$attachmentId': typeof AttachmentsAttachmentIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/calendar/$view': typeof CalendarViewRoute
  '/mail/compose': typeof MailComposeRoute
  '/mail/search': typeof MailSearchRoute
  '/calendar/': typeof CalendarIndexRoute
  '/mail/': typeof MailIndexRoute
  '/api/webhooks/nylas': typeof ApiWebhooksNylasRoute
  '/mail/f/$folderId': typeof MailFFolderIdRouteWithChildren
  '/mail/f/$folderId/t/$threadId': typeof MailFFolderIdTThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/api/version': typeof ApiVersionRoute
  '/attachments/$attachmentId': typeof AttachmentsAttachmentIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/calendar/$view': typeof CalendarViewRoute
  '/mail/compose': typeof MailComposeRoute
  '/mail/search': typeof MailSearchRoute
  '/calendar': typeof CalendarIndexRoute
  '/mail': typeof MailIndexRoute
  '/api/webhooks/nylas': typeof ApiWebhooksNylasRoute
  '/mail/f/$folderId': typeof MailFFolderIdRouteWithChildren
  '/mail/f/$folderId/t/$threadId': typeof MailFFolderIdTThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/calendar': typeof CalendarRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/mail': typeof MailRouteWithChildren
  '/api/version': typeof ApiVersionRoute
  '/attachments/$attachmentId': typeof AttachmentsAttachmentIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/calendar/$view': typeof CalendarViewRoute
  '/mail/compose': typeof MailComposeRoute
  '/mail/search': typeof MailSearchRoute
  '/calendar/': typeof CalendarIndexRoute
  '/mail/': typeof MailIndexRoute
  '/api/webhooks/nylas': typeof ApiWebhooksNylasRoute
  '/mail/f/$folderId': typeof MailFFolderIdRouteWithChildren
  '/mail/f/$folderId/t/$threadId': typeof MailFFolderIdTThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/healthz'
    | '/login'
    | '/logout'
    | '/mail'
    | '/api/version'
    | '/attachments/$attachmentId'
    | '/auth/callback'
    | '/calendar/$view'
    | '/mail/compose'
    | '/mail/search'
    | '/calendar/'
    | '/mail/'
    | '/api/webhooks/nylas'
    | '/mail/f/$folderId'
    | '/mail/f/$folderId/t/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/healthz'
    | '/login'
    | '/logout'
    | '/api/version'
    | '/attachments/$attachmentId'
    | '/auth/callback'
    | '/calendar/$view'
    | '/mail/compose'
    | '/mail/search'
    | '/calendar'
    | '/mail'
    | '/api/webhooks/nylas'
    | '/mail/f/$folderId'
    | '/mail/f/$folderId/t/$threadId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calendar'
    | '/healthz'
    | '/login'
    | '/logout'
    | '/mail'
    | '/api/version'
    | '/attachments/$attachmentId'
    | '/auth/callback'
    | '/calendar/$view'
    | '/mail/compose'
    | '/mail/search'
    | '/calendar/'
    | '/mail/'
    | '/api/webhooks/nylas'
    | '/mail/f/$folderId'
    | '/mail/f/$folderId/t/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  CalendarRoute: typeof CalendarRouteWithChildren
  HealthzRoute: typeof HealthzRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  MailRoute: typeof MailRouteWithChildren
  ApiVersionRoute: typeof ApiVersionRoute
  AttachmentsAttachmentIdRoute: typeof AttachmentsAttachmentIdRoute
  ApiWebhooksNylasRoute: typeof ApiWebhooksNylasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail/': {
      id: '/mail/'
      path: '/'
      fullPath: '/mail/'
      preLoaderRoute: typeof MailIndexRouteImport
      parentRoute: typeof MailRoute
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/'
      fullPath: '/calendar/'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof CalendarRoute
    }
    '/mail/search': {
      id: '/mail/search'
      path: '/search'
      fullPath: '/mail/search'
      preLoaderRoute: typeof MailSearchRouteImport
      parentRoute: typeof MailRoute
    }
    '/mail/compose': {
      id: '/mail/compose'
      path: '/compose'
      fullPath: '/mail/compose'
      preLoaderRoute: typeof MailComposeRouteImport
      parentRoute: typeof MailRoute
    }
    '/calendar/$view': {
      id: '/calendar/$view'
      path: '/$view'
      fullPath: '/calendar/$view'
      preLoaderRoute: typeof CalendarViewRouteImport
      parentRoute: typeof CalendarRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/attachments/$attachmentId': {
      id: '/attachments/$attachmentId'
      path: '/attachments/$attachmentId'
      fullPath: '/attachments/$attachmentId'
      preLoaderRoute: typeof AttachmentsAttachmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail/f/$folderId': {
      id: '/mail/f/$folderId'
      path: '/f/$folderId'
      fullPath: '/mail/f/$folderId'
      preLoaderRoute: typeof MailFFolderIdRouteImport
      parentRoute: typeof MailRoute
    }
    '/api/webhooks/nylas': {
      id: '/api/webhooks/nylas'
      path: '/api/webhooks/nylas'
      fullPath: '/api/webhooks/nylas'
      preLoaderRoute: typeof ApiWebhooksNylasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail/f/$folderId/t/$threadId': {
      id: '/mail/f/$folderId/t/$threadId'
      path: '/t/$threadId'
      fullPath: '/mail/f/$folderId/t/$threadId'
      preLoaderRoute: typeof MailFFolderIdTThreadIdRouteImport
      parentRoute: typeof MailFFolderIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CalendarRouteChildren {
  CalendarViewRoute: typeof CalendarViewRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
}

const CalendarRouteChildren: CalendarRouteChildren = {
  CalendarViewRoute: CalendarViewRoute,
  CalendarIndexRoute: CalendarIndexRoute,
}

const CalendarRouteWithChildren = CalendarRoute._addFileChildren(
  CalendarRouteChildren,
)

interface MailFFolderIdRouteChildren {
  MailFFolderIdTThreadIdRoute: typeof MailFFolderIdTThreadIdRoute
}

const MailFFolderIdRouteChildren: MailFFolderIdRouteChildren = {
  MailFFolderIdTThreadIdRoute: MailFFolderIdTThreadIdRoute,
}

const MailFFolderIdRouteWithChildren = MailFFolderIdRoute._addFileChildren(
  MailFFolderIdRouteChildren,
)

interface MailRouteChildren {
  MailComposeRoute: typeof MailComposeRoute
  MailSearchRoute: typeof MailSearchRoute
  MailIndexRoute: typeof MailIndexRoute
  MailFFolderIdRoute: typeof MailFFolderIdRouteWithChildren
}

const MailRouteChildren: MailRouteChildren = {
  MailComposeRoute: MailComposeRoute,
  MailSearchRoute: MailSearchRoute,
  MailIndexRoute: MailIndexRoute,
  MailFFolderIdRoute: MailFFolderIdRouteWithChildren,
}

const MailRouteWithChildren = MailRoute._addFileChildren(MailRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  CalendarRoute: CalendarRouteWithChildren,
  HealthzRoute: HealthzRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  MailRoute: MailRouteWithChildren,
  ApiVersionRoute: ApiVersionRoute,
  AttachmentsAttachmentIdRoute: AttachmentsAttachmentIdRoute,
  ApiWebhooksNylasRoute: ApiWebhooksNylasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
