export const MAIL_HOME_PATH = '/'
export const AUTH_PATH = '/auth'
export const CALENDAR_HOME_PATH = '/calendar'
export const CONTACTS_HOME_PATH = '/contacts'
export const SETTINGS_PATH = '/settings'
export const LOGIN_PATH = '/login'
export const DEFAULT_MAIL_FOLDER_ID = 'inbox'
