#!/usr/bin/env node
// Regenerate the design-sync barrel entry from cfg.componentSrcMap.
// The barrel must live INSIDE the app package (so the converter resolves PKG_DIR
// there and the components' `#…` subpath imports resolve) — it is gitignored and
// rebuilt by this script. Run before package-build on a fresh clone / re-sync:
//   node .design-sync/gen-entry.mjs
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'

const cfg = JSON.parse(readFileSync('.design-sync/config.json', 'utf8'))
const entryPath = cfg.entry // repo-root-relative, e.g. labs/ownmail/packages/app/design-sync-entry.tsx
const pkgDir = dirname(entryPath) // the app package dir
const lines = Object.values(cfg.componentSrcMap).map((srcRel) => {
	// srcRel is package-relative (e.g. src/shared/components/ui/button.tsx)
	const rel = relative(pkgDir, join(pkgDir, srcRel)).replace(/\.(tsx|ts|jsx|js)$/, '')
	return `export * from './${rel}'`
})
const banner = [
	'// GENERATED by .design-sync/gen-entry.mjs from cfg.componentSrcMap — do not edit by hand.',
	'// design-sync barrel entry for the claude.ai/design converter. Not part of the app build.',
	'',
].join('\n')
writeFileSync(entryPath, banner + [...new Set(lines)].join('\n') + '\n')
console.error(`wrote ${entryPath} (${lines.length} export lines)`)
