import { fileURLToPath } from 'node:url'
import react from '@vitejs/plugin-react'
import { defineConfig } from 'vitest/config'

// Dedicated test config. Deliberately does NOT load the cloudflare / tanstackStart /
// tailwind build plugins from vite.config.ts — those transform the whole app for the
// Workers runtime and are incompatible with v8 coverage instrumentation. Tests exercise
// the app's logic modules and React components directly, so only the React plugin is needed.
//
// Environment defaults to node (matching the modules under test); component tests opt into
// jsdom with a `// @vitest-environment jsdom` docblock at the top of the file.
export default defineConfig({
	plugins: [react()],
	resolve: {
		alias: {
			// `cloudflare:workers` is a virtual module supplied by @cloudflare/vite-plugin in
			// real builds; stub it for tests so platform.ts can resolve the dynamic import.
			'cloudflare:workers': fileURLToPath(new URL('./test/cloudflare-workers-stub.ts', import.meta.url)),
		},
	},
	test: {
		environment: 'node',
		globals: false,
		include: ['src/**/*.test.{ts,tsx}'],
		setupFiles: ['./test/setup.ts'],
		coverage: {
			provider: 'v8',
			reporter: ['text', 'text-summary', 'html'],
			include: ['src/**/*.{ts,tsx}'],
			exclude: [
				'src/**/*.test.{ts,tsx}',
				// Generated by TanStack Router — not hand-written, regenerated on build.
				'src/routeTree.gen.ts',
				// Ambient type declarations — no runtime code.
				'src/env.d.ts',
				// Build-target shim: aliased in for `cloudflare:workers` in the local Node SSR
				// target purely to throw at import time. Its only other line (an unreachable
				// `export const env = {}` after the throw) can never execute, so 100% is
				// unattainable and there is nothing meaningful to unit-test.
				'src/server/cloudflare-workers.local.ts',
			],
			thresholds: {
				lines: 100,
				functions: 100,
				branches: 100,
				statements: 100,
			},
		},
	},
})
